# -*- coding: utf-8 -*-
"""tp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUPJCO2Z-nOcy1apZU4CK2JGdrMdmyTB
"""

from typing import Dict

class InferenceEngine:
    """Expert system for hardware and software diagnostics."""


    def __init__(self):
        self.knowledge_base: Dict[str, bool] = {}

    def collect_fact(self, key: str, question: str) -> bool:
        """Prompts user for input and stores the boolean fact."""
        while True:
            res = input(f"{question} (y/n): ").lower().strip()
            if res in ['y', 'yes', 'o', 'oui']:
                self.knowledge_base[key] = True
                return True
            if res in ['n', 'no', 'non']:
                self.knowledge_base[key] = False
                return False
            print("(!) Invalid input. Please answer with 'y' or 'n'.")

    def process_diagnostic(self) -> str:
        """Analyzes the facts to return a recommendation."""
        kb = self.knowledge_base

        if not kb.get('power_on'):
            if kb.get('is_laptop') and not kb.get('charge_led'):
                return "Anomalie : Absence d'alimentation. Vérifier le bloc secteur ou la batterie."
            return "Anomalie : Problème électrique. Vérifier la source d'alimentation murale."

        if kb.get('black_screen'):
            return "Anomalie : Défaut d'affichage. Vérifier la connectique vidéo (HDMI/DP) ou le GPU."

        if kb.get('high_temp') and kb.get('sluggish'):
            return "Anomalie : Étranglement thermique. Nettoyage des dissipateurs requis."

        if kb.get('network_issue'):
            if kb.get('other_devices_ok'):
                return "Anomalie : Interface réseau locale défaillante (Pilotes ou matériel)."
            return "Anomalie : Panne réseau externe. Redémarrer l'équipement de routage."

        return "Résultat : Aucune erreur critique détectée. Analyse logicielle recommandée."

def run_diagnostic():
    engine = InferenceEngine()
    print("=== SYSTEME EXPERT : MAINTENANCE ET DIAGNOSTIC ===\n")

    # Questioning Phase
    is_laptop = engine.collect_fact('is_laptop', "L'appareil est-il un ordinateur portable ?")
    power_on = engine.collect_fact('power_on', "L'appareil s'allume-t-il ?")

    if not power_on:
        if is_laptop:
            engine.collect_fact('charge_led', "Le voyant de charge est-il actif ?")
    else:
        engine.collect_fact('black_screen', "L'affichage est-il inexistant (écran noir) ?")
        engine.collect_fact('high_temp', "Le système dégage-t-il une chaleur excessive ?")
        engine.collect_fact('sluggish', "Le système présente-t-il des lenteurs importantes ?")
        if engine.collect_fact('network_issue', "La connectivité réseau est-elle défaillante ?"):
            engine.collect_fact('other_devices_ok', "Les autres équipements accèdent-ils au Web ?")

    # Result Phase
    conclusion = engine.process_diagnostic()
    print("\n" + "="*40)
    print(f"RAPPORT FINAL : {conclusion}")
    print("="*40)

if __name__ == "__main__":
    run_diagnostic()

